### ISSUE TITLE
start-another-application

### ISSUE THREAD

**Issue by colin2wang** [colin2wang/code-playground#11]
好的，我们可以进一步扩展功能，让程序接受命令行参数，并将这些参数传递给 YAML 文件中定义的命令。在 YAML 文件中，可以通过`{args}`占位符来引用这些参数。

以下是更新后的完整项目代码和配置文件：

项目结构

```
my_project/
├── Cargo.toml
├── src/
│   └── main.rs
└── config.yml
```

1.`Cargo.toml`

```toml
[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
winapi = { version = "0.3", features = ["wincon", "winuser"] }
```

2.`config.yml`
更新后的 YAML 文件，支持`{args}`占位符：

```yaml
hide_console: true
wait_for_keypress: true
commands:
  - "notepad.exe {args}"
  - "calc.exe {args}"
```

3.`src/main.rs`
更新后的代码，支持命令行参数传递：

```rust
use serde::Deserialize;
use std::env;
use std::fs::File;
use std::io::{self, Read};
use std::process::Command;
use winapi::um::wincon::GetConsoleWindow;
use winapi::um::winuser::{ShowWindow, SW_HIDE};

#[derive(Debug, Deserialize)]
struct Config {
    hide_console: bool,
    wait_for_keypress: bool,
    commands: Vec<String>,
}

fn load_config_from_yaml(file_path: &str) -> Config {
    let mut file = File::open(file_path).expect("Failed to open YAML file");
    let mut contents = String::new();
    file.read_to_string(&mut contents).expect("Failed to read YAML file");

    let config: Config = serde_yaml::from_str(&contents).expect("Failed to parse YAML");
    config
}

fn hide_console_window() {
    unsafe {
        let window = GetConsoleWindow();
        if !window.is_null() {
            ShowWindow(window, SW_HIDE);
        }
    }
}

fn main() {
    // 加载 YAML 文件中的配置
    let config = load_config_from_yaml("config.yml");

    // 获取命令行参数（跳过第一个参数，即程序路径）
    let args: Vec<String> = env::args().skip(1).collect();
    let args_str = args.join(" ");

    // 根据全局配置决定是否隐藏控制台
    if config.hide_console {
        hide_console_window();
    }

    // 启动配置中的程序
    for command in config.commands {
        // 替换 {args} 占位符
        let command = command.replace("{args}", &args_str);

        let mut parts = command.split_whitespace();
        if let Some(program) = parts.next() {
            let args = parts.collect::<Vec<&str>>();
            Command::new(program)
                .args(&args)
                .spawn()
                .expect(&format!("Failed to start command: {}", command));
        }
    }

    println!("All commands started successfully.");

    // 根据全局配置决定是否等待用户按键
    if config.wait_for_keypress {
        println!("Press any key to exit...");
        let _ = io::stdin().read(&mut [0]).expect("Failed to read stdin");
    }
}
```

4.编译和运行

1. 安装 Rust：确保你已经安装了 Rust 编译器和 Cargo。

2. 创建项目：在终端中运行以下命令创建项目：

```bash
   cargo new my_project
   cd my_project
   ```

3. 添加文件：将上述代码分别保存到`Cargo.toml`、`src/main.rs`和`config.yml`中。

4. 编译项目：

```bash
   cargo build
   ```

5. 运行项目：

```bash
   cargo run arg1 arg2 arg3
   ```

5.项目说明

• 命令行参数：

• 使用`std::env::args()`获取命令行参数。

• 将参数拼接成字符串，并替换 YAML 文件中的`{args}`占位符。

• 全局配置：

• `hide_console`：控制是否隐藏控制台窗口。

• `wait_for_keypress`：控制程序执行完成后是否需要按任意键才能关闭控制台。

• 灵活性：通过 YAML 文件中的`{args}`占位符，可以灵活地将命令行参数传递给目标命令。

6.注意事项

• 如果需要跨平台支持，可以使用条件编译来处理不同操作系统的差异。

• 如果命令中包含特殊字符（如引号），需要确保 YAML 文件中的命令格式正确。

• 如果`wait_for_keypress`设置为`true`，程序会等待用户按键后退出；否则，程序会立即退出。

通过这种方式，你可以将命令行参数传递给 YAML 文件中定义的命令，从而实现更灵活的程序控制。
